### ISSUE TITLE
Make bash source work when using remote ssh connection

### ISSUE THREAD

**Issue by mikkoyli** [ouspg/cloudfuzzer#15]
Currently bash source function (in bastion) doesn't get executed when using non-interactive shell.
This should be investigated.

Following line could be commented in .bashrc in order for source to work but this might not be proper use of .bashrc because it is meant for interactive shells
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

```
mikko@mikko-Latitude-E6230:~$ ssh ubuntu@104.199.xx.xx "cloudfuzzer"
bash: cloudfuzzer: command not found
```

**Comment by evilon** [comment]
Could it be that you have different $PATH when not running interactively? 

```ssh  ubuntu@104.199.xx.xx 'echo $PATH'```  <-- Does PATH contain the location where cloudfuzzer is?

(Sorry if you knew this already, not sure if you referred to shell's "source" builtin command.)

**Comment by mikkoyli** [comment]
Thanks for commenting but cloudfuzzer is defined in functions.bash.inc as a bash function:
See: https://github.com/ouspg/cloudfuzzer/blob/master/bastion/functions.bash.inc#L6

Yes, I referred shell's source command

**Comment by mikkoyli** [comment]
http://unix.stackexchange.com/questions/4921/sh-startup-files-over-ssh/4953#4953
