### ISSUE TITLE
Lock and document cloudfuzzer commands

### ISSUE THREAD

**Issue by attekett** [ouspg/cloudfuzzer#19]
In this point of development we start to have a clear picture which of the current commands are "permanent" and could be locked.

Current functions.bash.inc, for remote-machine, has following command:

```
Available commands:
	bastion <command> - run <command> on bastion
	create-keys - create new vm-keys for packer build
	get-results - get results from cloudfuzzer
	get-stats - get various stats and logs from cloudfuzzer fuzzvm docker swarm
	help - print this
	send-docker-data <directory> - send docker data directory to bastion
	ssh - ssh to bastion
```

I suggest we lock these commands and start to add documentation/examples for them.

**Comment by mikkoyli** [comment]
Closing issue. Current commands are now locked and documented.
